<a href="https://colab.research.google.com/github/shivamtyagi577/DataScientist101/blob/main/Customers_Who_Never_Order.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
#Define the Customers Dataframe

customers_data = {'id'  : [1, 2, 3, 4],
                  'name': ['Joe', 'Henry', 'Sam', 'Max']}
customers_df = pd.DataFrame(customers_data)

customers_df

   id   name
0   1    Joe
1   2  Henry
2   3    Sam
3   4    Max

In [3]:
from typing_extensions import OrderedDict
# Define the Orders DataFrame
orders_data = {'id'        : [1, 2],
               'customerId': [3, 1]}
orders_df = pd.DataFrame(orders_data)

orders_df

   id  customerId
0   1           3
1   2           1

In [5]:
#Perform a left join to find customers without orders
merged_df = pd.merge(customers_df, orders_df, left_on= 'id', right_on = 'customerId', how = 'left')
merged_df

   id_x   name  id_y  customerId
0     1    Joe   2.0         1.0
1     2  Henry   NaN         NaN
2     3    Sam   1.0         3.0
3     4    Max   NaN         NaN

In [6]:
# Filter customers who have no matching order
no_orders_df = merged_df[merged_df['customerId'].isna()]
no_orders_df

   id_x   name  id_y  customerId
1     2  Henry   NaN         NaN
3     4    Max   NaN         NaN

In [7]:
result = no_orders_df[['name']].rename(columns={'name' : 'Customers'})
print(result)

  Customers
1     Henry
3       Max